
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_zenxl?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
